---
abstract: 'RDF Node class for XMLLiterals'
author:
  - 'Kjetil Kjernsmo <kjetilk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  Carp: 0
  ExtUtils::MakeMaker: 6.42
  XML::LibXML: 0
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-Trine-Node-Literal-XML
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Error: 0
  RDF::Trine: 0.111
  Scalar::Util: 0
  XML::LibXML: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.15
